### ISSUE TITLE
No error handling for gunzip errors

### ISSUE THREAD

**Issue by glasser** [kevva/decompress-targz#7]
(This probably applies to other decompress plugins as well.)

decompress-targz doesn't register an error handler on the gunzip stream, so any errors in gunzipping are thrown by some random callback rather than attached to the Promise returned by decompress.

See https://github.com/glasser/decompress/commit/e42dc127beac8d6d6b539f635e98e15118ca420c for a failing test demonstrating this issue.

**Comment by kevva** [comment]
Thanks for reporting. I've fixed it and added a test here https://github.com/kevva/decompress-targz/blob/master/test.js#L37-L41.
